### ISSUE TITLE
End of Tri 2 Checklist

### ISSUE THREAD

**Issue by SRIHITAKOTT1213** [SRIHITAKOTT1213/APCSP-Blog-Assignment#16]
- [ ] Finish 5.5-5.6 Blog
- [ ] Create night of the museum blog
- [ ] Organize tags
- [ ] Deployment and make sure everything is working
- [ ] Figure out presentation for Monday
